env: "local" # local, dev, prod
http_server:
  address: "0.0.0.0:8000"
  timeout: 10s
  idle_timeout: 60s
  user: "abdu1bari"
  password: "7721"

nats-streaming:
  host : "nats-streaming"
  port : "4222"
  user : "nats"
  password : "nats"
  cluster_id : "test-cluster"

database:
  host : "app-db"
  port : "5432"
  user : "postgres"
  password : "postgres"
  dbname : "l0"

migrations:
dir: "./migrations"
table: "schema_migrations"

redis:
  host : "app-redis"
  port : "6379"
  user : ""
  password : ""
